apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://charts.bitnami.com/bitnami
    name: nginx-ingress-controller
    releaseName: nginx-ingress-controller
    valuesFile: values.yaml
    version: 10.5.2
