apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: external-dns

resources:
  - "namespace.yaml"

helmCharts:
  - repo: https://charts.bitnami.com/bitnami
    name: external-dns
    releaseName: external-dns
    namespace: external-dns
    valuesFile: values.yaml
    version: 6.34.2
