apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


helmCharts:
  - repo: https://grafana.github.io/helm-charts
    name: grafana/grafana
    releaseName: grafana/grafana
    valuesFile: values.yaml
    version: 7.3.11
