apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: ad-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: devadsvc=953523290929.dkr.ecr.eu-central-1.amazonaws.com/ad-service:dev
    argocd-image-updater.argoproj.io/devadminapp.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-cred
    argocd-image-updater.argoproj.io/write-back-target: "kustomization:/microservices/ad-service/overlays/dev"
    argocd-image-updater.argoproj.io/devadminapp.force-update: "true"
spec:
  destination:
    server: https://D7A30105F6FE978E1C4343BC415F35AA.gr7.eu-central-1.eks.amazonaws.com
    namespace: webservice
  project: default
  source:
    plugin:
      name: kustomized-helm
    path: microservices/ad-service/overlays/dev
    repoURL: ""
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ServerSideApply=true
