apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: admin-frontend-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: devadminapp=public.ecr.aws/g0k9k2a6/front-end:dev
    argocd-image-updater.argoproj.io/devadminapp.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-cred
    argocd-image-updater.argoproj.io/write-back-target: "kustomization:/microservices/frontend-service/overlays/dev"
    argocd-image-updater.argoproj.io/devadminapp.force-update: "true"
spec:
  destination:
    server: https://8163BB1F9F0C9E9CA97578A675922B13.yl4.eu-west-2.eks.amazonaws.com
    namespace: webservice
  project: default
  source:
    plugin:
      name: kustomized-helm
    path: microservices/admin-frontend-service/overlays/dev
    repoURL: "https://gitlab.com/dareyio-live/devops/gitops.git"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ServerSideApply=true
