apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: external-dns
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  project: default
  source:
    # plugin:
    #   name: kustomized-helm
    path: gitops-proj/external-dns/overlays/stg
    repoURL: "https://github.com/MayorFaj/E-Commerce-Project.git"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ServerSideApply=true
