apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: currency-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: stgcurrency=953523290929.dkr.ecr.eu-central-1.amazonaws.com/currencyservice:stg
    argocd-image-updater.argoproj.io/stgcurrency.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-cred
    argocd-image-updater.argoproj.io/write-back-target: "kustomization:/microservices/currency-service/overlays/stg"
    argocd-image-updater.argoproj.io/stgcurrency.force-update: "true"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: webservice
  project: default
  source:
    plugin:
      name: kustomized-helm
    path: gitops-proj/microservices/currency-service/overlays/stg
    repoURL: "https://github.com/MayorFaj/E-Commerce-Project.git"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ServerSideApply=true
