apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: redis-service
  namespace: argocd
  # annotations:
  #   argocd-image-updater.argoproj.io/image-list: devadminapp=249269726433.dkr.ecr.eu-west-2.amazonaws.com/revamp_admin_frontend_service:dev
  #   argocd-image-updater.argoproj.io/devadminapp.update-strategy: digest
  #   argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-cred
  #   argocd-image-updater.argoproj.io/write-back-target: "kustomization:/microservices/redis-service/overlays/dev"
  #   argocd-image-updater.argoproj.io/devadminapp.force-update: "true"
spec:
  destination:
    server: https://5F424147AF13362ABEE30227DB514E70.gr7.eu-central-1.eks.amazonaws.com
    namespace: webservice
  project: default
  source:
    plugin:
      name: kustomized-helm
    path: microservices/redis-service/overlays/stg
    repoURL: "https://github.com/MayorFaj/E-Commerce-Project/gitops-proj"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ServerSideApply=true
