apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: email-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: stgemail=953523290929.dkr.ecr.eu-central-1.amazonaws.com/emailservice:stg
    argocd-image-updater.argoproj.io/stgemail.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-cred
    argocd-image-updater.argoproj.io/write-back-target: "kustomization:/microservices/email-service/overlays/stg"
    argocd-image-updater.argoproj.io/stgemail.force-update: "true"
spec:
  destination:
    server: https://5F424147AF13362ABEE30227DB514E70.gr7.eu-central-1.eks.amazonaws.com
    namespace: webservice
  project: default
  source:
    plugin:
      name: kustomized-helm
    path: microservices/email-service/overlays/stg
    repoURL: "https://github.com/MayorFaj/E-Commerce-Project/gitops-proj"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ServerSideApply=true
