apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://prometheus-community.github.io/helm-charts
    name: prometheus-community/prometheus
    releaseName: prometheus-community/prometheus
    valuesFile: values.yaml
    version: 25.21.0
