apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://charts.jetstack.io
    name: cert-manager
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml
    version: 1.14.2
