apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-image-updater

helmCharts:
  - repo: https://argoproj.github.io/argo-helm
    name: argocd-image-updater
    releaseName: argocd-image-updater
    valuesFile: values.yaml
    version: 0.9.4
