apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://grafana.github.io/helm-charts
    name: grafana/loki
    releaseName: grafana/loki
    valuesFile: values.yaml
    version: 6.5.2
