name: GO
env:
  AWS_REGION: eu-central-1               
  ECR_REPOSITORY: checkout-service
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v4
    # Restore cache at the beginning of the workflow
    # - 
    #   name: Restore Cache
    #   uses: actions/cache@v3
    #   with:
    #     path: |
    #       ~/.cache/go-build
    #       ~/go/pkg/mod
    #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    #     restore-keys: |
    #       ${{ runner.os }}-go-
    - 
      name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    # - 
    #   name: Build
    #   run: go build -v ./...
    - 
      name: GO Unit Tests
      timeout-minutes: 10
      run: |
        for SERVICE in "shippingservice" "productcatalogservice" "frontend" "checkoutservice"; do
        echo "testing $SERVICE..."
        pushd ../app-source-code/$SERVICE
        go build ./...
        go test -v ./... 